---
# tasks file for locust - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ locust_debian_pre_reqs }} as pre-requisite.
  package:
    name: "{{ locust_debian_pre_reqs }}"
    state: "{{ locust_debian_pre_reqs_desired_state }}"
    force_apt_get: yes

- name: Debian/Ubuntu Family | Installing {{ locust_app_debian_package }}
  pip:
    executable: "{{ pip_executable }}"
    name: "{{ locust_app_debian_package }}"
    state: "{{ locust_desired_state }}"
